### ISSUE TITLE
Errors on code

### ISSUE THREAD

**Issue by Zakabaka** [numz/sd-wav2lip-uhq#19]
I update the extension change the video and audio (mp4 and mp3 files)
But the program load something for a 10 mon and then gaves me an errors. See attached file
CVould you please advice what is the problem and how to get rid of it.
![Screenshot 2023-08-13 121001](https://github.com/numz/sd-wav2lip-uhq/assets/83984191/396be859-a250-4abd-8ea1-59bb42162b3e)

**Comment by numz** [comment]
Hi,
Sorry about this issue.
like it says at the end of the logs it seems there is an image in your video that doesn't have a detectable face, you can find the missing frame in "extensions\sd-wav2lip-uhq\scripts\wav2lip\temp\faulty_frame.jpg"
For provide this error, edit your video with your video editor and remove this image or split it to only have detectable face in it.

Let me know :)

**Comment by Zakabaka** [comment]
in video there are some transitions, so the person talks a bit then there is a transition to the next topic of conversation and the transition is like a dark screen for less than a second. May that be an issue? does the video whoul have a static scene/background with no transitions or scene changes?

**Comment by numz** [comment]
The challenge is that every frame needs to have a face, otherwise, it will cause an error. To circumvent this, you should segment your video into separate parts and arrange audio for each segment using a video editing software.

I close this issue because it's not one, you have to prepare stuff before send it to wav2lip.
Regards
